# Generated by Django 5.0.2 on 2024-03-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_subjects_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello_world.class')),
            ],
        ),
        migrations.CreateModel(
            name='CreditByStudent',
            fields=[
                ('credit', models.CharField(max_length=100)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello_world.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello_world.student')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherByClass',
            fields=[
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello_world.class')),
                ('subjects_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello_world.subjects')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello_world.teacher')),
            ],
        ),
    ]
